name: mcnd_mobile
description: MCND Mosque mobile app

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # HTTP Client
  dio: ^4.0.0
  pretty_dio_logger: ^1.1.1

  freezed_annotation: ^0.14.1

  # Utility Functions
  enum_to_string: ^2.0.1
  strings: ^0.2.1
  hijri:
    git: # move to null safty
      url: https://github.com/ahmedoid/hijri_date
      ref: 2c5342c90cd423488583ee2ce9f3c43db42b0fbe

  # Dependency Injection
  get_it: ^6.0.0
  injectable: ^1.2.2

  # State management
  hooks_riverpod: ^0.13.1+1
  flutter_hooks: ^0.16.0
  state_notifier: ^0.7.0

  # i18n & date formatting
  intl: ^0.17.0

  # json serialization
  json_annotation: ^4.0.1

  # analyzer annotation
  meta: ^1.3.0

  # Extra Icons
  material_design_icons_flutter: 5.0.5955-rc.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
  build_runner: ^1.12.2
  freezed: ^0.14.1+1
  injectable_generator: ^1.2.2
  json_serializable: ^4.1.0
  mockito: ^5.0.3
  flutter_launcher_icons: ^0.9.0
  flutter_gen_runner:

flutter_icons:
  android: true
  ios: true
  image_path: assets/app_logo.png

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
